name: minecraftGames
version: '${version}'
main: plugin.minecraftgames.MinecraftGames
api-version: 1.19
commands:
  shinkeisuijaku:
  shinkeisuijaku-scorelist:
  shinkeisuijaku-showpairs:
  orelmining:
  orelmining-scorelist:
  treasurehunt:
  treasurehunt-scorelist:
  initPlayer:
  randomTeleport:
  initialPosition: